name: gh pages

on:
  pull_request:
    branches:
      - main

jobs:
  build-deploy-gh-pages:
    name: Build / Deploy to gh-pages and Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: yarn install
        run: |
          yarn install
      - name: yarn build
        run: |
          yarn build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: website/build
          allow_empty_commit: true
      - name: Set PR Number
        id: pr_number
        run: echo "::set-output name=pr_number::${{ github.event.pull_request.number }}"
      - name: Generate Preview URL
        id: preview_url
        run: echo "::set-output name=url::https://${{ github.actor }}.github.io/${{ github.repository }}/${{ steps.pr_number.outputs.pr_number }}"
      - name: Display Preview URL
        run: echo "Preview URL: ${{ steps.preview_url.outputs.url }}"
