name: gh pages

on:
  pull_request:
    branches:
      - main

jobs:
  build-deploy-gh-pages:
    name: Build / Deploy to gh-pages and Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: yarn install
        run: |
          yarn install
      - name: yarn build
        run: |
          yarn build
      - name: Deploy to gh-pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: pr-${{ github.event.pull_request.number }}
          build_dir: website/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
